version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: nodevault-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: NodeVaultDB
    networks:
      - nodevault-net

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nodevault-backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - nodevault-net

volumes:
  mongo-data:

networks:
  nodevault-net:
    driver: bridge
